    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: first-client
  sleuth:
    sampler:
      probability: 1
management: 
    security: 
        enabled: false
